# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random((2,3,5))

In [4]:
# Method 2
aa=np.random.rand(2,3,5)

In [5]:
# Method 3
aaa=np.random.rand(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.67304835, 0.17786668, 0.40990207, 0.23915362, 0.2587613 ],
        [0.24212329, 0.34976004, 0.88854101, 0.04474321, 0.14634701],
        [0.49475594, 0.3070271 , 0.65199489, 0.08898928, 0.87303989]],

       [[0.5720453 , 0.65220765, 0.72775968, 0.65023635, 0.17256509],
        [0.18554337, 0.9635527 , 0.27100101, 0.60646802, 0.54303221],
        [0.30888484, 0.08609858, 0.13244161, 0.74336932, 0.06516145]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
#b=np.ones((5,2,3))
b=np.full((5,2,3),1)

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size==b.size)
print('size of a is :',a.size,'and size of b is:',b.size)

True
size of a is : 30 and size of b is: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print(a.shape==b.shape)
print('shape of a is :',a.shape,'and shape of b is:',b.shape)
print('they can not be add')

False
shape of a is : (2, 3, 5) and shape of b is: (5, 2, 3)
they can not be add


In [11]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = np.transpose(b, (1, 2, 0))
c.shape
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d=np.add(a,c)
print('It works now cause the 2 arrays have the same shape')

It works now cause the 2 arrays have the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print('A')
print(a)
print('D')
print(d)

A
[[[0.67304835 0.17786668 0.40990207 0.23915362 0.2587613 ]
  [0.24212329 0.34976004 0.88854101 0.04474321 0.14634701]
  [0.49475594 0.3070271  0.65199489 0.08898928 0.87303989]]

 [[0.5720453  0.65220765 0.72775968 0.65023635 0.17256509]
  [0.18554337 0.9635527  0.27100101 0.60646802 0.54303221]
  [0.30888484 0.08609858 0.13244161 0.74336932 0.06516145]]]
D
[[[1.67304835 1.17786668 1.40990207 1.23915362 1.2587613 ]
  [1.24212329 1.34976004 1.88854101 1.04474321 1.14634701]
  [1.49475594 1.3070271  1.65199489 1.08898928 1.87303989]]

 [[1.5720453  1.65220765 1.72775968 1.65023635 1.17256509]
  [1.18554337 1.9635527  1.27100101 1.60646802 1.54303221]
  [1.30888484 1.08609858 1.13244161 1.74336932 1.06516145]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e=np.multiply(a,c)
e

array([[[0.67304835, 0.17786668, 0.40990207, 0.23915362, 0.2587613 ],
        [0.24212329, 0.34976004, 0.88854101, 0.04474321, 0.14634701],
        [0.49475594, 0.3070271 , 0.65199489, 0.08898928, 0.87303989]],

       [[0.5720453 , 0.65220765, 0.72775968, 0.65023635, 0.17256509],
        [0.18554337, 0.9635527 , 0.27100101, 0.60646802, 0.54303221],
        [0.30888484, 0.08609858, 0.13244161, 0.74336932, 0.06516145]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
print(a==e)
print('Yes a is equal to e')

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
Yes a is equal to e


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_max =np.max(d)
d_min =np.min(d)
d_mean =np.mean(d)
print('d_max =',d_max)
print('d_min =',d_min)
print('d_mean =',d_mean)

d_max = 1.963552697213898
d_min = 1.0447432140476538
d_mean = 1.4175473614994645


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
# your code here
it = np.nditer(d, flags=['multi_index'])
while not it.finished:
    if it[0] == d_min:
        f[it.multi_index] = 0
    elif it[0] > d_min and it[0] < d_mean:
        f[it.multi_index] = 25
    elif it[0] == d_mean:
        f[it.multi_index] = 50
    elif it[0] > d_mean and it[0] < d_max:
        f[it.multi_index] = 75
    else:
        f[it.multi_index] = 100
    it.iternext()

In [20]:
#other solution
'''it = np.nditer(d, flags=['multi_index'])
while not it.finished:
    f[it.multi_index]= 0 if it[0]==d_min else 25 if it[0]<d_mean else 50 if it[0]==d_mean else 75 if it[0]<d_max else 100
    it.iternext'''

"it = np.nditer(d, flags=['multi_index'])\nwhile not it.finished:\n    f[it.multi_index]= 0 if it[0]==d_min else 25 if it[0]<d_mean else 50 if it[0]==d_mean else 75 if it[0]<d_max else 100\n    it.iternext"

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here
print('D')
print(d)
print('F')
print(f)

D
[[[1.67304835 1.17786668 1.40990207 1.23915362 1.2587613 ]
  [1.24212329 1.34976004 1.88854101 1.04474321 1.14634701]
  [1.49475594 1.3070271  1.65199489 1.08898928 1.87303989]]

 [[1.5720453  1.65220765 1.72775968 1.65023635 1.17256509]
  [1.18554337 1.9635527  1.27100101 1.60646802 1.54303221]
  [1.30888484 1.08609858 1.13244161 1.74336932 1.06516145]]]
F
[[[ 75.  25.  25.  25.  25.]
  [ 25.  25.  75.   0.  25.]
  [ 75.  25.  75.  25.  75.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25. 100.  25.  75.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
# your code here
g=np.empty((2,3,5),dtype=str)
it = np.nditer(d, flags=['multi_index'])
while not it.finished:
    g[it.multi_index]= "A" if it[0]==d_min else "B" if it[0]<d_mean else "C" if it[0]==d_mean else "D" if it[0]<d_max else "E"
    it.iternext()
    
#it = np.nditer(d, flags=['multi_index'])
#while not it.finished:
#    if it[0] == d_min:
#        g[it.multi_index] = "A";
#    elif it[0] > d_min and it[0] < d_mean:
#        g[it.multi_index] = "B"
#    elif it[0] == d_mean:
#        g[it.multi_index] = "C";
#    elif it[0] > d_mean and it[0] < d_max:
#        g[it.multi_index] = "D"
#    else:
#        g[it.multi_index] = "E"
#    it.iternext()

In [23]:
print('G')
print(g)

G
[[['D' 'B' 'B' 'B' 'B']
  ['B' 'B' 'D' 'A' 'B']
  ['D' 'B' 'D' 'B' 'D']]

 [['D' 'D' 'D' 'D' 'B']
  ['B' 'E' 'B' 'D' 'D']
  ['B' 'B' 'B' 'D' 'B']]]


In [24]:
g

array([[['D', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'D', 'A', 'B'],
        ['D', 'B', 'D', 'B', 'D']],

       [['D', 'D', 'D', 'D', 'B'],
        ['B', 'E', 'B', 'D', 'D'],
        ['B', 'B', 'B', 'D', 'B']]], dtype='<U1')